version: "3"
services:
  api:
    image: node:latest
    working_dir: /code
    ports:
      - 8000:8000
    environment:
      - PGUSER=megamindUser
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=users
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm run dev"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=megamindUser
      - POSTGRES_PASSWORD=password
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
volumes:
  dbdata: